disabled_rules:
  - trailing_whitespace
  - line_length
  - type_body_length
  - file_length
  - function_body_length
  - cyclomatic_complexity
  - nesting

opt_in_rules:
  - empty_count
  - closure_spacing
  - first_where
  - implicit_return
  - modifier_order
  - operator_usage_whitespace
  - sorted_first_last
  - toggle_bool
  - yoda_condition

included:
  - Sources
  - Tests

excluded:
  - .build
  - Packages
  - DerivedData

identifier_name:
  min_length:
    warning: 2
    error: 1
  excluded:
    - id
    - x
    - y
    - z
    - i
    - j
    - r
    - g
    - b
